SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `dbborgest`.`puntodeventa` ADD COLUMN `puntoventa_controladorfiscalmodelo` INT(3) NULL DEFAULT -1  AFTER `sucursal_id` , ADD COLUMN `puntoventa_controladorfiscalpuerto` INT(3) NULL DEFAULT -1  AFTER `puntoventa_controladorfiscalmodelo` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
