SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `documentosventas` ADD COLUMN `documentoventa_equipo1` VARCHAR(45) NULL DEFAULT ""  AFTER `documentoventa_listaprecio` , ADD COLUMN `documentoventa_equipo2` VARCHAR(45) NULL DEFAULT ""  AFTER `documentoventa_equipo1` , ADD COLUMN `documentoventa_formapago` VARCHAR(255) NULL "" NULL  AFTER `documentoventa_equipo2` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
